version: "3"

services:
  # mysql:
  #   image: mysql:latest
   
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/data
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'example'
  #     MYSQL_USER: 'user'
  #     MYSQL_PASSWORD: 'example'
  #     MYSQL_DATABASE: 'database'
  # redis:
  #   image: redis:latest
  #   restart: always
  #   command: redis-server --save 20 1 --loglevel warning --requirepass REDISPASS
  #   ports:
  #     - "6379:6379"      
  merchantmachine:
    build: MerchantMachine/
    ports:
      - "8000:8000"
    networks:
      - pouzikov

    
  dblayer:
    build: DBLayer/
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: database
    # depends_on:
    #   - mysql
    networks:
      - pouzikov

networks:
  pouzikov:
    driver: bridge

volumes:
  mysql_data:
  redis:
