version: "3"

services:
  mysql:
    image: mysql:latest
   
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/data
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'example'
      MYSQL_DATABASE: 'database'
    networks:
      - pouzikov

  merchantmachine:
    build: MerchantMachine/
    ports:
      - "8000:8000"
    depends_on:
      - dblayer
    networks:
      - pouzikov

  adminmerchant:
    build: Admin/
    ports:
      - "8001:8001"
    networks:
      - pouzikov
    depends_on:
    - merchantmachine
  
  customer-representative-manager:
    build: Customer-Representative-Manager/
    ports:
    - "8002:8002"
    networks:
    - pouzikov
    depends_on:
      - merchantmachine

  inventory-system-management:
    build: Inventory/
    ports:
    - "8004:8004"
    networks:
    - pouzikov
    depends_on:
      - dblayer
    
  dblayer:
    build: DBLayer/
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: database
    depends_on:
      - mysql
    networks:
    - pouzikov
  # redis:
  #   image: redis:latest
  #   restart: always
  #   command: redis-server --save 20 1 --loglevel warning --requirepass REDISPASS
  #   ports:
  #     - "6379:6379" 

networks:
  pouzikov:
    driver: bridge

volumes:
  mysql_data:
